from .resources.config import NrThesesMetadataResourceConfig
from .resources.resource import NrThesesMetadataResource
from .services.config import NrThesesMetadataServiceConfig
from .services.service import NrThesesMetadataService

NR_THESES_METADATA_RESOURCE_CONFIG = NrThesesMetadataResourceConfig
NR_THESES_METADATA_RESOURCE_CLASS = NrThesesMetadataResource
NR_THESES_METADATA_SERVICE_CONFIG = NrThesesMetadataServiceConfig
NR_THESES_METADATA_SERVICE_CLASS = NrThesesMetadataService
